### ISSUE TITLE
422 error message

### ISSUE THREAD

**Issue by mchl-schrdng** [looker-open-source/micro-admin-for-looker#5]
Hey !

Having trouble to establish the connexion between http://localhost:3000 and the Looker instance (myinstance.cloud.looker.com). Please find below the upcoming error message:

status: 422,
  message: 'POST myinstance.cloud.looker.com/oauth_client_apps/micro-admin-for-looker API returned a 422 status code'

Just added http://localhost:3000 in the embedded domain allowlist but still not working.

Thanks for your job and your help.

**Comment by fabio-looker** [comment]
I'll see if I can repro this on my end. Should be able to take a look at this by the end of the week.

If you can share any of the following, it may help:
- Your Looker version
- You config file, minus any sensitive properties, privately via email to fabble@google.com

**Comment by mchl-schrdng** [comment]
Hey thanks @fabio-looker, no hurry.
Version is 22.16.31 and config will be posted in a couple of minutes on your email address.

**Comment by fabio-looker** [comment]
Hi @mchl-schrdng 

Lots of things going on here since it was a while since I had updated this repo...

1. Node slightly changed the way it returns response headers in the native "https" module, which was breaking things on newer versions of Node. This was not your issue, but I fixed it while I was working on the repo ( 7a5d31278acc9dd3129585d41ddeb87966d8c1cb )
2. Looker's API has greatly improved its error messaging recently, and my hand-written API function was not exposing the detailed error messaging, so now if you re-run this, you will see more descriptive error messaging (  b45f98e61a37a4b91fec7f294bed7835e0f8927e )
3. The actual cause for your error seems to be that in 22.16, only "https" URLs are be allowed for oauth client redirect URIs. I am not sure if this is an intentional policy change (probaby), and I will ask around, but the quickest solution for you will be to run the micro-admin front-end with https, so you can provide an accepted redirect URI
4. You have not yet run into this error, but in your config, the key in the "host" object should be used when referring to a host, as in the primaryHostId setting
